name: "worker-build: update"

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-worker-build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update worker-build
        id: update
        run: |
          cd worker-build
          nix run github:Mic92/nix-update -- default --flake
          if git diff --quiet; then
            echo "No updates available"
            exit 0
          fi
          echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.update.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore(deps): update worker-build package'
          title: 'Update worker-build to latest version'
          body: |
            This PR updates the worker-build package to its latest version.
            
            This update was performed automatically by the weekly dependency update workflow.
          branch: update-worker-build
          delete-branch: true
          labels: dependencies
